#!/usr/bin/env bash
# Bash script that displays information about the subdomain and domain name

parse () {
    domain="$2.$1"
    subdomain="$2"
    res="$(dig "$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $1,$4,$5}')"
    record="$(echo "$res" | awk '{print $2}')"
    ip="$(echo "$res" | awk '{print $3}')"
    printf "The subdomain %s is a %s record and points to %s\n" "$subdomain" "$record" "$ip"
}

if [ $# -eq 2 ]
then
    parse "$1" "$2"
elif [ $# -eq 1 ]
then
    parse "$1" "www"
    parse "$1" "lb-01"
    parse "$1" "web-01"
    parse "$1" "web-02"
fi
