#!/usr/bin/env bash
# install nginx and set the route / to return Hello World

apt-get update
apt-get install nginx -y
sed -i -e "s/location \//location \/redirect_me/" -e "s/try_files \$uri \$uri\/ =404/rewrite ^\/redirect_me$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent/" /etc/nginx/sites-available/default
service nginx start
