#!/usr/bin/env bash
# install nginx and set the route / to return Hello World
text=" rewrite ^\/redirect_me$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"

apt-get update
apt-get install nginx -y
sed -i "/listen \[::\]:80 default_server;/a $text" /etc/nginx/sites-available/default
service nginx start
