#!/usr/bin/env bash
# install nginx and redirects a route
apt-get update
apt-get install nginx -y
echo "Hello World" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx start
