#!/usr/bin/env bash
# Bash script that creates the file /var/run/myscript.pid and deletes it
sudo sh -c "echo '$$' > '/var/run/myscript.pid'"
trap "echo 'I hate the kill command' && sudo rm '/var/run/myscript.pid' && exit 0" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "sudo rm '/var/run/myscript.pid' && exit 0" SIGQUIT
while true
do
	echo "To infinity and beyond"
	sleep 2
done
