#!/usr/bin/env bash
FILE="/etc/passwd"
while read -r line
do
	username=$(echo "$line" | cut -d ':' -f1)
	userid=$(echo "$line" | cut -d ':' -f3)
	homedir=$(echo "$line" | cut -d ':' -f6)
	echo "$username:$userid:$homedir"
done < "$FILE"
