#!/usr/bin/env bash
#Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line
i=0
while [ $i -lt 10 ]
do
	echo "Best School"
	if [[ $i -eq 8 ]]
	then
		echo "Hi"
	fi
	((i++))
done

