#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes
hours=0
minutes=1
while [ $hours -le 12 ]
do
	echo "Hour: $hours"
	minutes=1
	while [ $minutes -lt 60 ]
	do
		echo "$minutes"
		((minutes++))
	done
	((hours++))
done
