#!/usr/bin/env bash
#Checks if a school file exists
FILE=school
if [ -e "$FILE" ]
then
	echo "$FILE file exists"
	if [ ! -s "$FILE" ]
	then
		echo "$FILE file is empty"
	else
		echo "$FILE file is not empty"
	fi
	if [ -f "$FILE" ]
	then
		echo "$FILE school file is a regular file"
	fi
else
	echo "$FILE file does not exist"
fi
