#!/usr/bin/env bash
# Bash script that fixs the sandbox (Web stack debug 2)
pkill apache2
chown -R nginx:nginx /etc/nginx
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
